version: '3.8'
services:
  client:
    build: ./
    image: skillfactoryteam/vue-todos:1.0
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:8080/api
      - PORT=8081
    ports:
      - '8081:8081'
